services:
  puffweb:
    image: docker.io/nginx:latest
    restart: always
    pull_policy: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wwwroot:/opt/wwwroot:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-backend

networks:
  proxy-backend:
    external: true
